"""Generate the cloud's ML-KEM-768 key pair and write it to .env.

Docker Compose reads .env from the repository root automatically. The file
is listed in .gitignore and must never be committed: anyone holding the
private key can decrypt every reading sent from the gateway to the cloud.

Usage (needs the `cryptography` package, e.g. from requirements-dev.txt):

    python scripts/generate_keys.py           # refuses to overwrite .env
    python scripts/generate_keys.py --force   # new keys; the old ones stop working
"""

import argparse
import base64
from pathlib import Path

from cryptography.hazmat.primitives.asymmetric.mlkem import MLKEM768PrivateKey

ENV_FILE = Path(__file__).resolve().parent.parent / ".env"


def main():
    parser = argparse.ArgumentParser(description="Generate ML-KEM-768 keys into .env")
    parser.add_argument("--force", action="store_true", help="overwrite an existing .env")
    args = parser.parse_args()

    if ENV_FILE.exists() and not args.force:
        raise SystemExit(f"{ENV_FILE} already exists; use --force to replace its keys")

    private_key = MLKEM768PrivateKey.generate()
    private_seed = base64.b64encode(private_key.private_bytes_raw()).decode()
    public_key = base64.b64encode(private_key.public_key().public_bytes_raw()).decode()

    ENV_FILE.write_text(
        "# Generated by scripts/generate_keys.py. Never commit this file.\n"
        f"CLOUD_ML_KEM_PRIVATE_KEY={private_seed}\n"
        f"CLOUD_ML_KEM_PUBLIC_KEY={public_key}\n"
    )
    ENV_FILE.chmod(0o600)

    print(f"Wrote a new ML-KEM-768 key pair to {ENV_FILE}")


if __name__ == "__main__":
    main()
